In [ ]:
Q1. Write a Python function that takes in two arrays of data and calculates the F-value for a variance ratio
test. The function should return the F-value and the corresponding p-value for the test.

In [1]:
import numpy as np
from scipy.stats import f_oneway

In [2]:
def variance_ratio_test(data1, data2):
    # Perform variance ratio test (F-test)
    f_value, p_value = f_oneway(data1, data2)

    return f_value, p_value


In [3]:
group1_data = np.random.normal(loc=5, scale=2, size=100)
group2_data = np.random.normal(loc=7, scale=2, size=100)

In [4]:
group1_data

array([ 4.64366037,  3.43072839,  5.53946117,  6.06417967,  4.70613909,
        8.23564466,  5.7125257 ,  4.04322884,  3.25037265,  5.82081301,
        3.69986673,  7.96544852,  4.03938465,  4.9286091 ,  4.14845167,
        6.56831165,  1.62678424,  6.48806092,  2.62559381,  7.57395646,
        3.63612386,  4.12043914,  6.60364721,  6.46638468,  7.31693567,
        3.08115065,  4.06666159,  5.7640681 ,  5.171813  ,  2.47430151,
        3.87232132,  4.56156538,  7.2661843 ,  0.89127344,  7.74357351,
        5.5472101 ,  3.8056997 ,  5.56238899,  4.57191433,  3.35806797,
        6.73633138,  9.44185214,  6.14318419,  6.38469171,  3.85421482,
        4.62009958,  8.46688492,  5.09609408,  7.45799033, -0.17988992,
        3.72421829,  2.34249184,  7.84275643,  4.02298957,  4.80323904,
        1.7569069 ,  4.74694244,  2.66956412,  0.87633091,  9.17754837,
        7.81824077,  6.39545764,  5.25015738,  1.05773196,  5.42118394,
        4.49241633,  3.95936567,  4.44134143,  3.26708031,  5.40

In [5]:
group2_data

array([ 7.50801668,  6.82731447,  9.48219311,  8.5017573 ,  8.02180732,
       10.94773776,  9.92513021,  6.60369616,  9.02880302,  6.13368336,
        6.70899424,  6.97227679,  5.72831352,  6.7604292 ,  8.27392859,
        8.82333689,  9.20084092,  5.73636147,  8.11587702,  7.0006343 ,
        7.83024052,  3.61762322,  8.92799164,  4.74127928,  7.50715776,
        9.05456638,  7.47422057,  3.40192931,  7.22382166,  8.28389017,
        5.48162196,  6.93243527,  5.43731324,  3.34677351,  7.52218665,
        5.57368799,  8.38124792,  5.8851995 ,  9.10269138,  5.78388401,
        4.50159853,  8.59679601,  7.31015417,  7.43875136,  6.40299837,
        8.45405303,  6.4836366 ,  7.2370213 ,  9.6696375 ,  6.25103634,
        6.1638454 , 10.6415837 ,  3.98282602,  5.94571069,  6.83896586,
        7.94116599,  6.5482846 ,  8.5633619 ,  8.07245053,  5.56024627,
       11.28019081,  5.76852335,  7.21513892,  5.66450196,  4.63456596,
        3.96330943,  6.54556113,  7.06568071,  8.63272077,  6.38

In [6]:
f_value, p_value = variance_ratio_test(group1_data, group2_data)

In [7]:
# Display the results
print(f"F-value: {f_value}")
print(f"P-value: {p_value}")

F-value: 47.82951570356011
P-value: 6.266766318985354e-11


In [ ]:
Q2. Given a significance level of 0.05 and the degrees of freedom for the numerator and denominator of an
F-distribution, write a Python function that returns the critical F-value for a two-tailed test.

In [8]:
from scipy.stats import f

In [9]:
def critical_f_value(alpha, df_between, df_within):
    # Calculate the critical F-value
    critical_f = f.ppf(1 - alpha / 2, df_between, df_within)

    return critical_f


In [10]:
alpha = 0.05
df_between_example = 3
df_within_example = 20

In [11]:
critical_f = critical_f_value(alpha, df_between_example, df_within_example)

In [12]:
critical_f

3.8586986662732143

In [13]:
# Display the result
print(f"Critical F-value: {critical_f}")

Critical F-value: 3.8586986662732143


In [ ]:
Q3. Write a Python program that generates random samples from two normal distributions with known

variances and uses an F-test to determine if the variances are equal. The program should output the F-
value, degrees of freedom, and p-value for the test.

In [14]:
import numpy as np
from scipy.stats import f

In [15]:
def equal_variances_f_test(data1, data2):
    # Calculate variances
    var1 = np.var(data1, ddof=1)
    var2 = np.var(data2, ddof=1)

    # Check which variance is larger
    if var1 > var2:
        larger_var = var1
        smaller_var = var2
    else:
        larger_var = var2
        smaller_var = var1

    # Calculate F-value, degrees of freedom, and p-value
    f_value = larger_var / smaller_var
    df_num = len(data1) - 1
    df_denom = len(data2) - 1
    p_value = 2 * min(f.cdf(f_value, df_num, df_denom), 1 - f.cdf(f_value, df_num, df_denom))

    return f_value, df_num, df_denom, p_value


In [16]:
data1 = np.random.normal(loc=5, scale=2, size=50)
data2 = np.random.normal(loc=5, scale=3, size=50)

In [17]:
data1

array([ 9.00808495,  7.41238772,  4.4404037 ,  2.10638396,  5.86428865,
        0.2708862 ,  1.49144879,  2.33657139,  5.05615268,  5.89039154,
        4.74850013,  5.47384514,  6.52627819,  3.77942327,  2.9746898 ,
        4.33106315,  8.83322616,  7.56133623,  5.96976382,  2.94229665,
        4.76329675,  2.75103819,  7.54429694,  2.4221836 ,  4.45526897,
        5.1112632 ,  6.28120666,  4.18739598,  2.71201514,  7.49926792,
        2.82478183,  8.53333029,  5.52458979,  1.55996378,  9.2575883 ,
        4.73177194,  4.73581305,  4.48925816,  3.18244815,  1.4678115 ,
        5.58591537,  4.39998795,  3.51402865,  2.74994344,  5.22496812,
        6.79255183,  3.13997006,  5.07577313,  6.13466677, 10.83048502])

In [18]:
data2

array([ 6.23226989,  8.77983332,  6.3061523 ,  3.00885258,  4.72978804,
        8.05859935,  2.18642731,  0.87243494,  5.77460295,  3.8777176 ,
        6.47117838,  4.10294111,  3.58337602,  1.40417511,  3.61416527,
        6.02789387,  7.27551847,  4.75556106, -2.06496846,  5.28771195,
        4.24037921, 10.33273892,  6.80552714,  9.74481944,  3.51600702,
       11.52227896,  2.72285995,  4.58903293,  5.75384483,  1.98356676,
        2.90681736,  7.08445768,  1.92342385,  2.79068152,  3.5790209 ,
        8.06385732,  0.77345642,  5.29703644,  4.82856912,  3.80756952,
        4.07425037, -0.50701246,  2.45200694, -1.2241372 ,  0.52392147,
        3.96601032, 12.61856746,  3.78744686,  3.59856693,  5.20895721])

In [19]:
f_value, df_num, df_denom, p_value = equal_variances_f_test(data1, data2)

In [20]:
# Display the results
print(f"F-value: {f_value}")
print(f"Degrees of Freedom (numerator): {df_num}")
print(f"Degrees of Freedom (denominator): {df_denom}")
print(f"P-value: {p_value}")

F-value: 1.7725641627357915
Degrees of Freedom (numerator): 49
Degrees of Freedom (denominator): 49
P-value: 0.047702784641918905


In [ ]:
Q4.The variances of two populations are known to be 10 and 15. A sample of 12 observations is taken from
each population. Conduct an F-test at the 5% significance level to determine if the variances are
significantly different.

In [21]:
from scipy.stats import f


In [22]:
# Given data
variance1 = 10
variance2 = 15
sample_size = 12
alpha = 0.05

In [23]:
# Degrees of freedom
df1 = sample_size - 1
df2 = sample_size - 1

In [24]:
df1

11

In [25]:
df2

11

In [26]:
# F-statistic calculation
f_statistic = variance1 / variance2

In [27]:
f_statistic

0.6666666666666666

In [28]:
# P-value calculation
p_value = 2 * min(f.cdf(f_statistic, df1, df2), 1 - f.cdf(f_statistic, df1, df2))

In [29]:
p_value

0.5123897987357996

In [30]:
# Critical F-value for two-tailed test
critical_f_value = f.ppf(1 - alpha / 2, df1, df2)

In [31]:
critical_f_value

3.473699051085809

In [32]:
# Display the results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")
print(f"Critical F-value: {critical_f_value}")

F-statistic: 0.6666666666666666
P-value: 0.5123897987357996
Critical F-value: 3.473699051085809


In [33]:
# Compare with the significance level
if p_value < alpha:
    print("Reject the null hypothesis. Variances are significantly different.")
else:
    print("Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.")

Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.


In [ ]:
Q5. A manufacturer claims that the variance of the diameter of a certain product is 0.005. A sample of 25
products is taken, and the sample variance is found to be 0.006. Conduct an F-test at the 1% significance
level to determine if the claim is justified.

In [34]:
from scipy.stats import f

In [35]:
# Given data
claimed_variance = 0.005
sample_variance = 0.006
sample_size = 25
alpha = 0.01

In [36]:
# Degrees of freedom
df_numerator = sample_size - 1
df_denominator = 1  # Degrees of freedom for population variance


In [37]:
df_numerator

24

In [38]:
df_denominator

1

In [39]:
# F-statistic calculation
f_statistic = (sample_variance / claimed_variance)

In [40]:
# P-value calculation
p_value = 2 * min(f.cdf(f_statistic, df_numerator, df_denominator), 1 - f.cdf(f_statistic, df_numerator, df_denominator))

In [41]:
# Critical F-value for two-tailed test
critical_f_value = f.ppf(1 - alpha / 2, df_numerator, df_denominator)


In [42]:
# Display the results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")
print(f"Critical F-value: {critical_f_value}")

F-statistic: 1.2
P-value: 0.7407800760081285
Critical F-value: 24939.565259943236


In [45]:
# Compare with the significance level
if p_value < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis


In [ ]:
Q6. Write a Python function that takes in the degrees of freedom for the numerator and denominator of an
F-distribution and calculates the mean and variance of the distribution. The function should return the
mean and variance as a tuple.

In [46]:
def f_distribution_mean_variance(df_numerator, df_denominator):
    # Calculate mean
    mean = df_denominator / (df_denominator - 2)

    # Calculate variance
    variance = (2 * df_denominator**2 * (df_numerator + df_denominator - 2)) / (df_numerator * (df_denominator - 2)**2 * (df_denominator - 4))

    return mean, variance


In [47]:
df_numerator_example = 3
df_denominator_example = 20

In [48]:
df_numerator_example

3

In [49]:
df_denominator_example

20

In [50]:
mean, variance = f_distribution_mean_variance(df_numerator_example, df_denominator_example)


In [51]:
# Display the result
print(f"Mean of the F-distribution: {mean}")
print(f"Variance of the F-distribution: {variance}")

Mean of the F-distribution: 1.1111111111111112
Variance of the F-distribution: 1.0802469135802468


In [ ]:
Q7. A random sample of 10 measurements is taken from a normal population with unknown variance. The
sample variance is found to be 25. Another random sample of 15 measurements is taken from another
normal population with unknown variance, and the sample variance is found to be 20. Conduct an F-test
at the 10% significance level to determine if the variances are significantly different.

In [52]:
from scipy.stats import f


In [53]:
# Given data
sample_variance1 = 25
sample_size1 = 10
sample_variance2 = 20
sample_size2 = 15
alpha = 0.10

In [54]:
# Degrees of freedom
df_numerator = sample_size1 - 1
df_denominator = sample_size2 - 1

In [55]:
df_numerator

9

In [56]:
df_denominator

14

In [57]:
# F-statistic calculation
f_statistic = sample_variance1 / sample_variance2

In [58]:
# P-value calculation
p_value = 2 * min(f.cdf(f_statistic, df_numerator, df_denominator), 1 - f.cdf(f_statistic, df_numerator, df_denominator))

In [59]:
# Critical F-value for two-tailed test
critical_f_value = f.ppf(1 - alpha / 2, df_numerator, df_denominator)

In [60]:
# Display the results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")
print(f"Critical F-value: {critical_f_value}")

F-statistic: 1.25
P-value: 0.6832194382585954
Critical F-value: 2.6457907352338195


In [61]:
# Compare with the significance level
if p_value < alpha:
    print("Reject the null hypothesis. Variances are significantly different.")
else:
    print("Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.")

Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.


In [ ]:
Q8. The following data represent the waiting times in minutes at two different restaurants on a Saturday
night: Restaurant A: 24, 25, 28, 23, 22, 20, 27; Restaurant B: 31, 33, 35, 30, 32, 36. Conduct an F-test at the 5%
significance level to determine if the variances are significantly different.

In [62]:
from scipy.stats import f

In [63]:
# Given data
waiting_times_restaurant_A = [24, 25, 28, 23, 22, 20, 27]
waiting_times_restaurant_B = [31, 33, 35, 30, 32, 36]
alpha = 0.05

In [64]:
# Degrees of freedom
df_numerator = len(waiting_times_restaurant_A) - 1
df_denominator = len(waiting_times_restaurant_B) - 1


In [65]:
df_numerator

6

In [66]:
df_denominator

5

In [67]:
# Sample variances
sample_variance_A = sum((x - np.mean(waiting_times_restaurant_A))**2 for x in waiting_times_restaurant_A) / df_numerator
sample_variance_B = sum((x - np.mean(waiting_times_restaurant_B))**2 for x in waiting_times_restaurant_B) / df_denominator


In [68]:
sample_variance_A

7.80952380952381

In [69]:
sample_variance_B

5.366666666666667

In [70]:
# F-statistic calculation
f_statistic = sample_variance_A / sample_variance_B

In [71]:
# P-value calculation
p_value = 2 * min(f.cdf(f_statistic, df_numerator, df_denominator), 1 - f.cdf(f_statistic, df_numerator, df_denominator))


In [72]:
# Critical F-value for two-tailed test
critical_f_value = f.ppf(1 - alpha / 2, df_numerator, df_denominator)

In [73]:
# Display the results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")
print(f"Critical F-value: {critical_f_value}")

F-statistic: 1.4551907719609583
P-value: 0.6974815747937484
Critical F-value: 6.977701858535566


In [74]:
# Compare with the significance level
if p_value < alpha:
    print("Reject the null hypothesis. Variances are significantly different.")
else:
    print("Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.")

Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.


In [ ]:
Q9. The following data represent the test scores of two groups of students: Group A: 80, 85, 90, 92, 87, 83;
Group B: 75, 78, 82, 79, 81, 84. Conduct an F-test at the 1% significance level to determine if the variances
are significantly different.

In [75]:
import numpy as np
from scipy.stats import f

In [76]:
# Given data
test_scores_group_A = np.array([80, 85, 90, 92, 87, 83])
test_scores_group_B = np.array([75, 78, 82, 79, 81, 84])
alpha = 0.01


In [77]:

# Degrees of freedom
df_numerator = len(test_scores_group_A) - 1
df_denominator = len(test_scores_group_B) - 1

In [78]:
df_numerator

5

In [79]:
df_denominator

5

In [80]:
# Sample variances
sample_variance_A = np.var(test_scores_group_A, ddof=1)
sample_variance_B = np.var(test_scores_group_B, ddof=1)

In [81]:
sample_variance_A

19.76666666666667

In [82]:
sample_variance_B

10.166666666666666

In [83]:
# F-statistic calculation
f_statistic = sample_variance_A / sample_variance_B

In [84]:
# P-value calculation
p_value = 2 * min(f.cdf(f_statistic, df_numerator, df_denominator), 1 - f.cdf(f_statistic, df_numerator, df_denominator))

In [85]:
# Critical F-value for two-tailed test
critical_f_value = f.ppf(1 - alpha / 2, df_numerator, df_denominator)

In [86]:
# Display the results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")
print(f"Critical F-value: {critical_f_value}")


F-statistic: 1.9442622950819677
P-value: 0.4831043549070688
Critical F-value: 14.939605459912224


In [87]:
# Compare with the significance level
if p_value < alpha:
    print("Reject the null hypothesis. Variances are significantly different.")
else:
    print("Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.")

Fail to reject the null hypothesis. There is not enough evidence to conclude significant difference in variances.
